name: unit-tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S 4_Unit_testing -B 4_Unit_testing/build
      - name: Build
        run: cmake --build 4_Unit_testing/build --config Debug
      - name: Run tests
        run: ctest --output-on-failure
        working-directory: 4_Unit_testing/build
